version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  airflow-init:
    image: apache/airflow:2.9.2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor # 可以改為 CeleryExecutor 以使用 Redis
      AIRFLOW_UID: 50000 # 建議設置，以避免權限問題
      # --- 新增的環境變數 ---
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-amazon==6.0.0 boto3>=1.23.9"
      AWS_ACCESS_KEY_ID: "AWS Access Key ID" # <--- 請替換為你的 AWS Access Key ID
      AWS_SECRET_ACCESS_KEY: "AWS Secret Access Key" # <--- 請替換為你的 AWS Secret Access Key
      AWS_DEFAULT_REGION: "ap-northeast-1" # <--- 請替換為你的 AWS 區域 (例如: ap-southeast-1)
      # --- 結束新增 ---
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: /bin/bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && exit 0"
    # 這個服務會執行初始化命令後退出
  airflow-webserver:
    image: apache/airflow:2.9.2
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully # 確保初始化完成
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: 50000
      # --- 新增的環境變數 ---
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-amazon==6.0.0 boto3>=1.23.9"
      AWS_ACCESS_KEY_ID: "AWS Access Key ID" # <--- 請替換為你的 AWS Access Key ID
      AWS_SECRET_ACCESS_KEY: "AWS Secret Access Key" # <--- 請替換為你的 AWS Secret Access Key
      AWS_DEFAULT_REGION: "ap-northeast-1" # <--- 請替換為你的 AWS 區域 (例如: ap-southeast-1)
      # --- 結束新增 ---
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../:/usr/local/airflow/project_root # Mount the project root
    ports:
      - "8080:8080" # Airflow UI 介面
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
  airflow-scheduler:
    image: apache/airflow:2.9.2
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: 50000
      # --- 新增的環境變數 ---
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-amazon==6.0.0 boto3>=1.23.9"
      AWS_ACCESS_KEY_ID: "AWS Access Key ID" # <--- 請替換為你的 AWS Access Key ID
      AWS_SECRET_ACCESS_KEY: "AWS Secret Access Key" # <--- 請替換為你的 AWS Secret Access Key
      AWS_DEFAULT_REGION: "ap-northeast-1" # <--- 請替換為你的 AWS 區域 (例如: ap-southeast-1)
      # --- 結束新增 ---
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ../:/usr/local/airflow/project_root # Mount the project root
    command: scheduler
  
  
volumes:
  postgres_data: